package de.fast2work.mobility.utility.util

import java.text.SimpleDateFormat
import java.util.*

/**
 * This class contains all the constants value that is used in application
 * All values defined here, it can not be changed in application lifecycle
 */


object LocalConfig {
    const val PROFILE_IMAGE_SIZE = 1080
    const val IMAGE_WIDTH_SIZE = 1080
    const val PROFILE_IMAGE_QUALITY = 90 // Image Quality 90 percentage
    const val RESEND_OTP_DURATION: Long = 60L // Resend otp time 2 min
    const val GLIDE_TIMEOUT = 120000
    var SCREEN_HEIGHT = 0
    var SCREEN_WIDTH: Int = 0

    const val mobility_budget="mobility_budget"
    const val co2_management="co2_management"
    const val BOTH="both"
}

object PageCode {
    const val TERMS_CONDITIONS = "termsconditions"
    const val PRIVACY_POLICY = "privacypolicy"
    const val END_USER_AGREEMENT = "eula"
    const val SUBSCRIPTION_AGREEMENT = "subscriber_agreement"
}

object Media {
    const val PREFIX_PROFILE = "profile_"
    const val PREFIX_STATUS = "status_"
    const val EXTENSION_JPEG = "jpeg"
    const val EXTENSION_MP4 = "mp4"
    const val EXTENSION_PNG = "png"
    const val EXTENSION_PDF = "pdf"
    const val EXTENSION_TEXT = "txt"
    const val PREFIX_LIST = "list"
    const val PREFIX_GIF = "gif"
    const val PREFIX_IMAGE = "image"
    const val PREFIX_VIDEO = "video"
    const val PREFIX_AUDIO = "audio"
    const val PREFIX_PDF = "pdf"

    const val MIME_TYPE_IMAGE = "image/"
    const val MIME_TYPE_PDF = "application/pdf"
    const val MIME_TYPE_TEXT = "text/plain"
}

object Theme {
    const val THEME_YELLOW = "yellow"
    const val THEME_GREY = "grey"
    const val THEME_DARK = "dark"
}

object SignUpCompletedStep {
    const val SIGNUP_SCREEN = "1"
    const val OTP_SCREEN = "2"
    const val CREATE_PROFILE_SCREEN = "3"
    const val COMPLETE_PROFILE_SCREEN = "4"
    const val UPLOAD_ID_SCREEN = "5"
}


object RelationShipConstants {
    const val SINGLE = "Single"
    const val MARRIED = "Married"
    const val ENGAGED = "Engaged"
    const val IN_A_RELATIONSHIP = "In a Relationship"
}


val currentDate: String
    get() {
        val d = Date()
        return SimpleDateFormat("yyyy-MM-dd-HH-mm-ss-SSS", Locale.ENGLISH).format(d)
    }

interface IConstants {
    companion object {
        const val LIST_PERSONAL = "personal"
        const val TAGS_TICKET_MASTER = "TicketMaster"
        const val TAGS_MEET_UP = "MeetUp"
        const val FILE_DATA = "FILE_DATA"
        const val LIST_RECEIVED = "received"
        const val COUNT_ZERO = "0"
        const val ONE_HASHTAG = "#"
        const val WWW_INSTAGRAM_COM = "www.instagram.com/"
        const val WWW_FACEBOOK_COM = "www.facebook.com/"
        const val WWW_TWITTER_COM = "www.twitter.com/"
        const val WWW_PINTEREST_COM = "www.pinterest.com/"
        const val INSTAGRAM = "instagram"
        const val FACEBOOK = "facebook"

        //        const val TWITTER = "twitter"
        const val PINTEREST = "pinterest"
        const val BUNDLE_BITMAP = "bitmap"
        const val BITMAP_DATA = "BITMAP_DATA"
        const val DRAW_PATH_DATA = "DRAW_PATH_DATA"
        const val IS_FROM_EDIT = "FROM_EDIT"
        const val IS_FROM_SIGNUP = "IS_FROM_SIGNUP"
        const val COUNT_ONE = "1"
        const val ANDROID = "android"
        const val IMAGE = "image"
        const val HASHTAG = "hashtag"

        //        const val DURATION = "duration"
        const val SELECTED_LIST = "SELECTED_LIST"
        const val SELECTED_GROUP_CONNECTION_LIST = "SELECTED_GROUP_CONNECTION_LIST"
        const val GROUP_CONNECTION_LIST = "GROUP_CONNECTION_LIST"

        //        const val HASHTAG_ID = "hashtag_id"
        const val HASHTAG_RESPONSE = "HASHTAG_RESPONSE"
        const val EVENT_DATA = "event_data"
        const val EVENT_FILTER_DATA = "EVENT_FILTER_DATA"
        const val LIST_ID = "list_id"
        const val PAGE = "page"
        const val DRAW_IMAGE = "draw_image"
        const val USER_ID = "user_id"
        const val OTP_ID = "otp_id"
        const val VERIFY_OTP_TYPE = "VERIFY_OTP_TYPE"
        const val VERIFY_OTP_TYPE_CHANGE_EMAIL = "ChangeEmail"
        const val VERIFY_OTP_TYPE_SIGNUP = "SignUp"
        const val APP = "App"
        const val API_SUCCESS = "1"
        const val PHOTO = "photo"
        const val CONST_1 = "1"
        const val CONST_INT_1 = 1
        const val CONST_INT_99 = 99
        const val CONST_INT_4 = 4
        const val CONST_INT_2 = 2
        const val CONST_0 = "0"
        const val PAGE_LIMIT_20 = 20
        const val PAGE_LIMIT_10 = "10"
        const val GOOGLE = "google"
        const val PARAM_IMG = "image"
        const val PARAM_VIDEO = "video"
        const val PARAM_TAG = "tag"
        const val PARAM_IMAGE = "image"
        const val PARAM_POST_ID = "post_id"
        const val POST_ID = "post_id"
        const val PARAM_ADD_IMG_CONTACT_US = "image"
        const val PARAM_STEP_NUMBER = "step_number"
        const val EMAIL = "email"
        const val OTP = "otp"


        //        const val EMAIL_ADDRESS = "email_address"
        const val SYNC_TYPE = "sync_type"
        const val CALENDAR_SYNC_TYPE_GOOGLE = "Google"
        const val KEYWORD = "keyword"
        const val LATLNG = "latlong"
        const val START_DATE_TIME = "startDateTime"
        const val END_DATE_TIME = "endDateTime"
        const val GENRE_ID = "genreId"
        const val EVENT_RADIUS = "radius"
        const val TAGS = "tags"
        const val REC_LIMIT = "rec_limit"
        const val IS_APPROVE = "is_approve"
        const val CONNECTION_ID = "connection_id"
        const val PAGE_INDEX = "page_index"
        const val OTHER_USER_OBJECT = "other_user"
        const val DATE_FORMAT_YYYY_MM_DD_HH_MM_SS = "yyyy/MM/dd, HH:mm:ss"
        const val TYPE = "type"
        const val BUNDLE_POST_ID_FROM_DYNAMIC_LINK = "postIdFromDynamicLink"
        const val BUNDLE_IS_DEEP_LINK_FOR_SUBSCRIPTION = "isDeepLinkForSubscription"
        const val POSITION = "position"
        const val CURRENT = "current"
        const val TEXT = "text"
        const val ADD_CONNECTION = "Add Connection"
        const val WITHDRAW = "Withdraw"
        const val REMOVE_CONNECTION = "Remove Connection"
        const val THEME_DATA = "theme_data"
        const val THEME = "theme"
        const val DARK_MODE = "dark_mode"

        const val FIRST_NAME = "first_name"
        const val BUZZWORK = "Buzzwork"
        const val LAST_NAME = "last_name"
        const val DOB = "dob"
        const val PHONE_NUMBER = "phone_number"
        const val ADDRESS = "address"
        const val ZIPCODE = "zipcode"
        const val LAT = "lat"
        const val LONG = "long"
        const val PROFILE_PICTURE = "profile_picture"
        const val PROFILE_PIC = "profile_pic"
        const val GROUP_ID_DATA = "GROUP_ID_DATA"
        const val IS_ADD_PARTICIPATE = "IS_ADD_PARTICIPATE"
        const val CHAT_GROUP_DATA = "CHAT_GROUP_DATA"
        const val CONVERSATION_SID = "conversation_sid"
        const val REACTION_USERS_DATA = "reaction_users_data"


        const val FRONT_DOCUMENT = "front_document"
        const val BACK_DOCUMENT = "back_document"
        const val CONNECTION_USER_ID = "connection_user_id"
        const val NAME = "name"
        const val PARENT_ID = "parent_id"
        const val RECURRING_DATES = "recurring_dates"
        const val COMPLETED_TASK_DATES = "completed_task_dates"
        const val TASK_DATE = "task_date"
        const val IS_RECURRING_DATA = "is_recurring_data"
        const val IS_CURRENT_DATE_ALLOWED = "is_current_date_allowed"
        const val PROFILE_USER_ID = "profile_user_id"
        const val IS_ACCEPT = "is_accept"
        const val RELATIONSHIP_STATUS = "relationship_status"
        const val FACEBOOK_URL = "facebook_url"
        const val INSTAGRAM_URL = "instagram_url"
        const val TWITTER_URL = "twitter_url"
        const val PINTEREST_URL = "pinterest_url"
        const val REDDIT_URL = "reddit_url"
        const val SEND_FEEDBACK = "send_feedback"
        const val CONTACT_US = "contact_us"
        const val REPORT_USER = "report_user"
        const val ABOUT_US = "aboutus"
        const val IS_SHOW_BUTTON = "is_show_button"
        const val IS_ADD_BUTTON = "is_add_button"
        const val IS_EDIT_MEMO = "is_edit_memo"
        const val TITLE = "title"
        const val API_KEY = "apikey"
        const val DATE = "date"
        const val SYNC_CONTACT = "sync_contact"
        const val PROFILE_PRIVACY = "profile_privacy"
        const val ALLOW_SUBSCRIBE_PROFILE = "allow_subscribe_profile"
        const val ALLOW_SHARE_PROFILE = "allow_share_profile"
        const val WS_DEBUG = "ws_debug"
        const val POST_TYPE = "post_type"
        const val MY_POST = "my_post"
        const val IMAGE_URL = "image_url"
        const val CATEGORY = "category"
        const val HTTP = "http://"
        const val HTTPS = "https://"
        const val WWW = "www."
//        const val COM = ".com"
        const val BLOCK_USER_ID = "block_user_id"
        const val IS_BLOCK = "is_block"
        const val BLOCK = "Block"
        const val UN_BLOCK = "UnBlock"
        const val SINGLE_SPACE = " "
        const val GROUP = "Group"
        const val Individual = "Individual"
        const val YES = "yes"
        const val LINK = "link"
        const val STATUS = "status"
        const val DOCUMENTS = "documents[]"
        const val LIST = "list"
        const val TASK_ID = "task_id"
        const val TASK_ITEM = "tasksItem"
        const val PARTICIPANT = "participant"
        const val DOCUMENT_DATA = "document_data"
        const val DOCUMENT_DOWNLOAD = "document_download"
        const val CHECKED = "isChecked"
        const val START_TIME = "start_time"
        const val END_TIME = "end_time"
        const val TIME_SLOT = "time_slot"
        const val MONTH = "month"
        const val YEAR = "year"
        const val MEMO_ID = "memo_id"
        const val TASK_PARTICIPATE_REMOVE = "TASK_PARTICPANT_REMOVE"
        const val TASK_INVITE = "TASK_INVITE"
        const val TASK_REQUEST = "TASK_REQUEST"

        //LIST NOTIFICATION
        const val NOTIFICATION_ADD_LIST_PARTICIPANT = "ADD_LIST_PARTICIPANT"
        const val LIST_UPDATED = "LIST_UPDATED"
        const val NOTIFICATION_LIST_PARTICIPANT_ADDED = "LIST_PARTICIPANT_ADDED"
        const val NOTIFICATION_LIST_DELETED = "LIST_DELETED"


        //NEWS FEED
        const val NOTIFICATION_ADD_NEWS_CATEGORY = "ADD_NEWS_CATEGORY"
        const val NOTIFICATION_NOTIFY_NEWS_ARTICLE = "NOTIFY_NEWS_ARTICLE"

        //SIDE MENU
        const val NOTIFICATION_CONTACT_US_APPRECIATION = "CONTACT_US_APPRECIATION"
        const val NOTIFICATION_NOTIFY_SYNC_CONTACT = "NOTIFY_SYNC_CONTACT"


        const val TASK_PARTICIPANT_DELETE = "TASK_PARTICIPANT_DELETE"
        const val TASK_UPDATE = "TASK_UPDATE"

        const val TASK_DELETE = "TASK_DELETE"
        const val TASK_COMPLETE = "TASK_COMPLETE"
        const val CONNECTION_REQUEST = "CONNECTION_REQUEST"
        const val TAG_POST = "TAG_POST"
        const val ADD_NEW_POST = "ADD_NEW_POST"
        const val IS_FROM_TASK_DETAIL = "IS_FROM_TASK_DETAIL"
        const val IS_FROM_FEED_LIST = "IS_FROM_FEED_LIST"
        const val BUNDLE_KEY_MEDIA_URL = "media_url"
        const val BUNDLE_KEY_IS_FEED_EDIT = "is_feed_edit"
        const val BUNDLE_IMAGE_LIST = "image_list"
        const val BUNDLE_IMAGE_POSITION = "image_position"
        const val BUNDLE_PUSH_NOTIFICATION = "push_notification"
        const val BUNDLE_PUSH_IS_APP_IN_FOREGROUND_WHEN_NOTIFICATION_GENERATED = "is_app_in_foreground_when_notification_generated"
        const val BUNDLE_IS_FROM_CATEGORY = "is_from_category"
        const val BUNDLE_IS_FOR_REQUEST_RECEIVED = "is_for_request_received"
        const val BUNDLE_IS_FROM_LOGIN = "is_from_login"
        const val BUNDLE_IS_FROM_POST = "is_from_post"
        const val BUNDLE_IS_FROM_HABIT = "is_from_habit"
        const val BUNDLE_PATH_MODEL = "PATH_MODEL"
        const val BUNDLE_IS_FROM_EDIT = "is_from_app_edit"
        const val BUNDLE_LIST_CHILD_RESPONSE = "list_child_response"
        const val CONNECTION_REQUEST_APPROVED = "1"
        const val CONNECTION_REQUEST_REJECTED = "0"
        const val TASK_INVITE_ACCEPTED = "1"
        const val TASK_INVITE_DECLINED = "0"
        const val debouncePeriod = 500L
        const val BOTTOM_SHEET = "Bottom Sheet"
        const val PUSH_NOTIFICATION_TYPE_CONNECTION_REQUEST = "CONNECTION_REQUEST"
        const val PUSH_NOTIFICATION_TYPE_CONNECTION_ACCEPT = "CONNECTION_ACCEPT"
        const val PUSH_NOTIFICATION_TYPE_ADD_NEW_POST = "ADD_NEW_POST"
        const val PUSH_NOTIFICATION_TYPE_TAG_POST = "TAG_POST"
        const val PUSH_NOTIFICATION_TYPE_TASK_ACCEPT = "TASK_ACCEPT"
        const val PUSH_NOTIFICATION_TYPE_TASK_INVITE = "TASK_INVITE"
        const val PUSH_NOTIFICATION_TYPE_TASK = "TASK"
        const val PUSH_NOTIFICATION_TYPE_LINK_POST_REMINDER = "LINK_POST_REMINDER"
        const val PUSH_NOTIFICATION_TYPE_NOTIFY_PREMIUM_USER_POST = "NOTIFY_PREMIUM_USER_POST"
        const val PUSH_NOTIFICATION_TYPE_EVENT_TASK_NOTIFICATION = "EVENT_TASK_NOTIFICATION"
        const val PUSH_NOTIFICATION_TYPE_WEEKLY_WORKLOAD = "WEEKLY_WORKLOAD"
        const val PUSH_NOTIFICATION_TYPE_GROUP_NAME_UPDATED = "GROUP_NAME_UPDATED"
        const val PUSH_NOTIFICATION_TYPE_GROUP_CHAT_ADDED = "GROUP_CHAT_ADDED"
        const val PUSH_NOTIFICATION_TYPE_GROUP_CHAT_ACCEPTED = "GROUP_CHAT_ACCEPTED"
        const val PUSH_NOTIFICATION_TYPE_GROUP_CHAT_REJECTED = "GROUP_CHAT_REJECTED"
        const val PUSH_NOTIFICATION_TYPE_GROUP_CHAT_REMOVED = "GROUP_CHAT_REMOVED"
        const val PUSH_NOTIFICATION_TYPE_GROUP_CHAT_SELF_REMOVED = "GROUP_CHAT_SELF_REMOVED"
        const val PUSH_NOTIFICATION_TYPE_MESSAGE_REQUEST = "MESSAGE_REQUEST"
        const val PUSH_NOTIFICATION_TYPE_MESSAGE = "MESSAGE"

        const val BUNDLE_KEY_FEED_DATA = "feed_data"
        const val MY_POST_LIST = "my_post_list"
        const val IS_BOOLEN = "is_boolen"
        const val IS_START_FEED_TAB = "isStartFeedTab"
        const val IS_START_STATUS_TAB = "isStartStatusTab"
        const val IS_START_WEEK_TAB = "isStartWeekTab"
        const val CALENDAR_DATA = "calendar_data"
        const val IS_START_HOME_TAB = "isFromHomeTab"
        const val FILE_PATH = "FILE_PATH"
        const val TO_USER_ID = "to_user_id"
        const val CHAT_TYPE = "chat_type"
        const val GROUP_IMAGE = "group_image"
        const val GROUP_NAME = "group_name"


        const val PENDING = "Pending"
        const val ACCEPTED = "Accepted"
        const val REJECTED = "Rejected"
        const val APPROVED = "Approved"
        const val ZERO = "0"
        const val ONE = "1"
        const val TWO = "2"
        const val THREE = "3"
        const val FOUR = "4"
        const val VIDEO = "video"
        const val POST = "post"
        const val TAG = "tag"
        const val HOME = "1"
        const val NO_ITEM_FOUND = "No items found"
        const val PORTRAIT = 1
        const val LANDSCAPE = 2

//        const val SPLASH_DURATION = 2000L

        const val TRIM_VIDEO_PREFIX = "trimmedVideo_" //in seconds
        const val PREFIX_HIFUN = "-"
        const val EXTRA_INPUT_URI = "EXTRA_INPUT_URI"
        const val TRIM_SECOND = "TRIM_SECOND"
        const val VIDEO_LIMIT = 10 //in seconds
        const val VIDEO_EXTENSION = ".mp4" //in seconds
        const val TARGET_VIDEO_WIDTH = 540
        const val TARGET_VIDEO_HEIGHT = 960
        const val TARGET_VIDEO_BITRATE = 1500000

        //        const val TARGET_VIDEO_BITRATE = 5
        //        const val TARGET_FRAME_RATE = 30

        const val VIDEO_THUMB_DIRECTORY = "Thumb"
        const val OTHER_USER_GROUP_DATA = "other_user_group_data"
        const val GROUP_ID = "group_id"


        const val BOTTOM_SHEET_SHOWN = "BOTTOM_SHEET_SHOWN"
        const val PLAN_TYPE_FREE = "Free"
        const val PLAN_TYPE_PREMIUM = "Premium"
        const val PLAN_TYPE_PROPLANNER = "Proplanner"
        const val PREMIUM_PACKAGE_ID = "de.fast2work.mobility.premium"

        //STATUS CONSTANTS
        const val STATUS_TYPE = "type"
        const val STATUS_TEXT = "status_text"
        const val STATUS_SHARE_TYPE = "share_type"
        const val STATUS_SHARE_TO = "share_to"
        const val STATUS_GROUP_NAME = "group_name"
        const val STATUS_MAKE_GROUP = "make_group"
        const val STATUS_JSON_TEXT = "text_data"
        const val STATUS_TEXT_IMAGE = "text_image"
        const val STATUS_IMAGE = "status_file[]"
        const val STATUS_ID = "status_id"

        const val ACCOUNT_REJECTED = "account_rejected"
        const val ACCOUNT_APPROVED = "account_approved"


        const val SELECTED_STACK_1 = "selected_stack_1"
        const val SELECTED_STACK_2 = "selected_stack_2"
        const val SELECTED_STACK_3 = "selected_stack_3"

        //HABIT_CONSTANTS
        const val HABIT_TITLE = "habit_title"
        const val HABIT_CAT_ID = "habit_cat_id"
        const val HABIT_DATA = "habit_data"
        const val IS_FROM_HABIT = "isFromHabit"
        const val IS_EDIT = "isEdit"
        const val UPCOMING = "Upcoming"
        const val PRODUCTIVITY = "Productivity"
        const val MINDFULNESS = "Mindfulness"
        const val SELF_CARE = "Selfcare"
        const val WELLNESS = "Wellness"
        const val STATUS_COMPLETED = "Completed"
        const val NOTIFICATION_COUNT = "notification_count"

        //LIST_CONSTANTS
        const val IS_FROM_CHAT = "is_from_chat"

        //TASK_CONSTANTS
        const val IS_FROM_CREATE_TASK = "isFromCreateTask"

        //CHAT_CONSTANTS
        const val ATTRIBUTE_USERS = "users"
        const val ATTRIBUTE_NAME = "name"
        const val ATTRIBUTE_IDENTITY = "identity"
        const val ATTRIBUTE_STATUS = "status"
        const val ATTRIBUTE_TITLE = "title"
        const val ATTRIBUTE_IMAGE = "image"
        const val ATTRIBUTE_MESSAGE_TYPE = "message_type"
        const val ATTRIBUTE_MESSAGE_DATA = "message_data"
        const val ATTRIBUTE_REACTIONS = "reactions"
        const val ATTRIBUTE_CHAT_TYPE = "chat_type"
        const val ATTRIBUTE_PROFILE_IMAGE = "profile_image"
        const val ATTRIBUTE_FULL_NAME = "full_name"
        const val ATTRIBUTE_USER_NAME = "user_name"
        const val ATTRIBUTE_TASK_ICON = "task_icon"
        const val ATTRIBUTE_TASK_LOCATION = "task_location"
        const val ATTRIBUTE_START_TIME = "start_time"
        const val ATTRIBUTE_END_TIME = "end_time"
        const val ATTRIBUTE_ADDED_DATE = "added_date"
        const val ATTRIBUTE_STATUS_TYPE = "status_type"
        const val ATTRIBUTE_URL = "url"
        const val ATTRIBUTE_LINK = "link"
        const val ATTRIBUTE_NEWS_TITLE = "news_title"
        const val ATTRIBUTE_NEWS_IMAGE = "news_image"
        const val ATTRIBUTE_FIRST_NAME = "first_name"
        const val ATTRIBUTE_LAST_NAME = "last_name"

        const val INFO_CODE_HOME = "home"
        const val INFO_CODE_CALENDAR = "calendar"
        const val INFO_CODE_SOCIAL = "social"
        const val INFO_CODE_EVENTS = "events"
        const val INFO_CODE_LIST = "list"
        const val INFO_CODE_NEWSFEED = "newsfeed"
        const val INFO_CODE_HABIT = "habit"

        const val HEADER_NAME = "HeaderName"

    }
}

interface IConstantsIcon {
    companion object {
        const val D_ROTATION = "3d_rotation"
        const val AC_UNIT = "ac_unit"
        const val ACCESS_ALARM = "access_alarm"
        const val ACCESS_ALARMS = "access_alarms"
        const val ACCESS_TIME = "access_time"
        const val ACCESSIBILITY = "accessibility"
        const val ACCESSIBLE = "accessible"
        const val ACCOUNT_BALANCE = "account_balance"
        const val ACCOUNT_BALANCE_WALLET = "account_balance_wallet"
        const val ACCOUNT_BOX = "account_box"
        const val ACCOUNT_CIRCLE = "account_circle"
        const val ABD = "adb"
        const val ADD = "add"
        const val ADD_A_PHOTO = "add_a_photo"
        const val ADD_ALARM = "add_alarm"
        const val ADD_ALERT = "add_alert"
        const val ADD_BOX = "add_box"
        const val ADD_CIRCLE = "add_circle"
        const val ADD_CIRCLE_OUTLINE = "add_circle_outline"
        const val ADD_LOCATION = "add_location"
        const val ADD_SHOPPING = "add_shopping_cart"
        const val ADD_TO_PHOTOS = "add_to_photos"
        const val ADD_TO_QUEUE = "add_to_queue"
        const val ADJUST = "adjust"
        const val AIR_LINE_SEAT_FLAT = "airline_seat_flat"
        const val AIR_LINE_SEAT_FLAT_ANGLED = "airline_seat_flat_angled"
        const val AIR_LINE_SEAT_INDIVIDUAL_SUITE = "airline_seat_individual_suite"
        const val AIRLINE_SEAT_LEGROOM_EXTRA = "airline_seat_legroom_extra"
        const val AIRLINE_SEAT_LEGROOM_NORMAL = "airline_seat_legroom_normal"
        const val AIRLINE_SEAT_LEGROOM_REDUCED = "airline_seat_legroom_reduced"
        const val AIRLINE_SEAT_RECLINE_EXTRA = "airline_seat_recline_extra"
        const val AIRLINE_SEAT_RECLINE_NORMAL = "airline_seat_recline_normal"
        const val AIRPLANEMODE_ACTIVE = "airplanemode_active"
        const val AIRPLANEMODE_INACTIVE = "airplanemode_inactive"
        const val AIRPLAY = "airplay"
        const val AIRPORT_SHUTTLE = "airport_shuttle"
        const val ALARM = "alarm"
        const val ALARM_ADD = "alarm_add"
        const val ALARM_OFF = "alarm_off"
        const val ALARM_ON = "alarm_on"
        const val ALBUM = "album"
        const val ALL_INCLUSIVE = "all_inclusive"
        const val ALL_OUT = "all_out"
        const val ANDROID = "android"
        const val ANOUNCEMENT = "announcement"
        const val APPS = "apps"
        const val ARCHIVE = "archive"
        const val ARROW_BACK = "arrow_back"
        const val ARROW_DOWNWARD = "arrow_downward"
        const val ARROW_DOWN_WORD = "arrow_drop_down"
        const val ARROW_DOWN_WORD_CIRCLE = "arrow_drop_down_circle"
        const val ARROW_DROP_UP = "arrow_drop_up"
        const val ARROW_FORWARD = "arrow_forward"
        const val ARROW_UPWARD = "arrow_upward"
        const val ART_TRACK = "art_track"
        const val ASPECT_RATION = "aspect_ratio"
        const val ASSESSMENT = "assessment"
        const val ASSIGNMENT = "assignment"
        const val ASSIGNMENT_IND = "assignment_ind"
        const val ASSIGNMENT_LATE = "assignment_late"
        const val ASSIGNMENT_RETURN = "assignment_return"
        const val ASSIGNMENT_RETURNED = "assignment_returned"
        const val ASSIGNMENT_TURNED_IN = "assignment_turned_in"
        const val ASSISTANT = "assistant"
        const val ASSISTANT_PHOTO = "assistant_photo"
        const val ATTACH_FILE = "attach_file"
        const val ATTACH_MONEY = "attach_money"
        const val ATTACHMENT = "attachment"
        const val AUDIOTRACK = "audiotrack"
        const val AUTORENEW = "autorenew"
        const val AV_TIMER = "av_timer"
        const val BACKSPACE = "backspace"
        const val BACKUP = "backup"
        const val BATTERY_ALERT = "battery_alert"
        const val BATTERY_CHARGING_FULL = "battery_charging_full"
        const val BATTERY_FULL = "battery_full"
        const val BATTERY_STD = "battery_std"
        const val BATTERY_UNKNOWN = "battery_unknown"
        const val BEACH_ACCESS = "beach_access"
        const val BEENHERE = "beenhere"
        const val BLOCK = "block"
        const val BLUETOOTH = "bluetooth"
        const val BLUETOOTH_AUDIO = "bluetooth_audio"
        const val BLUETOOTH_CONNECTION = "bluetooth_connected"
        const val BLUETOOTH_DISABLED = "bluetooth_disabled"
        const val BLUETOOTH_SEARCHING = "bluetooth_searching"
        const val BLUR_CIRCULAR = "blur_circular"
        const val BLUR_LINEAR = "blur_linear"
        const val BLUR_OFF = "blur_off"
        const val BLUR_ON = "blur_on"
        const val BOOK = "book"
        const val BOOKMARK = "bookmark"
        const val BOOKMARK_BORDER = "bookmark_border"
        const val BOOKMARK_ALL = "border_all"
        const val BORDER_BOTTOM = "border_bottom"
        const val BORDER_CLEAR = "border_clear"
        const val BORDER_COLOR = "border_color"
        const val BORDER_HORIZONTAL = "border_horizontal"
        const val BORDER_INNER = "border_inner"
        const val BORDER_LEFT = "border_left"
        const val BORDER_OUTER = "border_outer"
        const val BORDER_RIGHT = "border_right"
        const val BORDER_STYLE = "border_style"
        const val BORDER_TOP = "border_top"
        const val BORDER_VERTICAL = "border_vertical"
        const val BRANDING_WATERMARK = "branding_watermark"
        const val BRIGHTENEES_1 = "brightness_1"
        const val BRIGHTENEES_2 = "brightness_2"
        const val BRIGHTENEES_3 = "brightness_3"
        const val BRIGHTENEES_4 = "brightness_4"
        const val BRIGHTENEES_5 = "brightness_5"
        const val BRIGHTENEES_6 = "brightness_6"
        const val BRIGHTENEES_7 = "brightness_7"
        const val BRIGHTENEES_AUTO = "brightness_auto"
        const val BRIGHTENEES_HIGH = "brightness_high"
        const val BRIGHTENEES_LOW = "brightness_low"
        const val BRIGHTENEES_MEDIUM = "brightness_medium"
        const val BROKEN_IMAGE = "broken_image"
        const val BRUSH = "brush"
        const val BUBBLE_CHART = "bubble_chart"
        const val BUG_REPORT = "bug_report"
        const val BUILD = "build"
        const val BURST_MODE = "burst_mode"
        const val BUSINESS = "business"
        const val BUSINESS_CENTER = "business_center"
        const val CACHED = "cached"
        const val CAKE = "cake"
        const val CALL = "call"
        const val CALL_END = "call_end"
        const val CALL_MADE = "call_made"
        const val CALL_MERGE = "call_merge"
        const val CALL_MISSED = "call_missed"
        const val CALL_MISSED_OUTGOING = "call_missed_outgoing"
        const val CALL_RECEIVED = "call_received"
        const val CALL_SPLIT = "call_split"
        const val CALL_TO_ACTION = "call_to_action"
        const val CAMERA = "camera"
        const val CAMERA_ALT = "camera_alt"
        const val CAMERA_ENHANCE = "camera_enhance"
        const val CAMERA_FRONT = "camera_front"
        const val CAMERA_REAR = "camera_rear"
        const val CAMERA_ROLL = "camera_roll"
        const val CANCEL = "cancel"
        const val CARD_GIFTCARD = "card_giftcard"
        const val CARD_MEMBERSHIP = "card_membership"
        const val CARD_TRAVEL = "card_travel"
        const val CASION = "casino"
        const val CAST = "cast"
        const val CAST_CONNECTION = "cast_connected"
        const val CENTER_FOCUS_STRONG = "center_focus_strong"
        const val CENTER_FOCUS_WEAK = "center_focus_weak"
        const val CHANGE_HISTORY = "change_history"
        const val CHAT = "chat"
        const val CHAT_BUBBLE = "chat_bubble"
        const val CHAT_BUBBLE_OUTLINE = "chat_bubble_outline"
        const val CHECK = "check"
        const val CHECK_BOX = "check_box"
        const val CHECK_BOX_OUTLINE_BLANK = "check_box_outline_blank"
        const val CHECK_CIRCLE = "check_circle"
        const val CHEVRON_LEFT = "chevron_left"
        const val CHEVRON_RIGHT = "chevron_right"
        const val CHILD_CARE = "child_care"
        const val CHILD_FRIENDLY = "child_friendly"
        const val CHROME_READER_MODE = "chrome_reader_mode"
        const val CLASS = "class"
        const val CLEAR = "clear"
        const val CLEAR_ALL = "clear_all"
        const val CLOSE = "close"
        const val CLOSE_CAPTION = "closed_caption"
        const val CLOUD = "cloud"
        const val CLOUD_CIRCLE = "cloud_circle"
        const val CLOUD_DONE = "cloud_done"
        const val CLOUD_DOWNLOAD = "cloud_download"
        const val CLOUD_OFF = "cloud_off"
        const val CLOUD_QUEUE = "cloud_queue"
        const val CLOUD_UPLOD = "cloud_upload"
        const val CODE = "code"
        const val COLLECTION = "collections"
        const val COLLECTION_BOOKMARK = "collections_bookmark"
        const val COLOR_LENS = "color_lens"
        const val COLORIZE = "colorize"
        const val COMMENT = "comment"
        const val COMPARE = "compare"
        const val COMPARE_ARROWS = "compare_arrows"
        const val COMPUTER = "computer"
        const val CONFIRMATION_NUMBER = "confirmation_number"
        const val CONTACT_MAIL = "contact_mail"
        const val CONTACT_PHONE = "contact_phone"
        const val CONTACTS = "contacts"
        const val CONTENT_COPY = "content_copy"
        const val CONTENT_CUT = "content_cut"
        const val CONTENT_PASTE = "content_paste"
        const val CONTENT_POINT = "control_point"
        const val CONTENT_POINT_DULICATE = "control_point_duplicate"
        const val COPYRIGHT = "copyright"
        const val CREATE = "create"
        const val CREATE_NEW_FOLDER = "create_new_folder"
        const val CREDIT_CARD = "credit_card"
        const val CROP = "crop"
        const val CROP_16_9 = "crop_16_9"
        const val CROP_3_2 = "crop_3_2"
        const val CROP_5_4 = "crop_5_4"
        const val CROP_7_5 = "crop_7_5"
        const val CROP_DIN = "crop_din"
        const val CROP_FREE = "crop_free"
        const val CROP_LANDSCAPE = "crop_landscape"
        const val CROP_ORIGINAL = "crop_original"
        const val CROP_PORTRAIT = "crop_portrait"
        const val CROP_ROTATE = "crop_rotate"
        const val CROP_SQUARE = "crop_square"
        const val DASHBOARD = "dashboard"
        const val DATA_USAGE = "data_usage"
        const val DATA_RANGE = "date_range"
        const val DEHAZE = "dehaze"
        const val DELETE = "delete"
        const val DELETE_FOREVER = "delete_forever"
        const val DELETE_SWEEP = "delete_sweep"
        const val DESCRIPTION = "description"
        const val DESKTOP_MAC = "desktop_mac"
        const val DESKTOP_WINDOWS = "desktop_windows"
        const val DETAILS = "details"
        const val DEVELOPER_BOARD = "developer_board"
        const val DEVELOPER_MODE = "developer_mode"
        const val DEVICE_HUB = "device_hub"
        const val DEVICE = "devices"
        const val DEVICE_OTHER = "devices_other"
        const val DIALER_SIP = "dialer_sip"
        const val DIALPAD = "dialpad"
        const val DIRECTIONS = "directions"
        const val DIRECTIONS_BIKE = "directions_bike"
        const val DIRECTIONS_BOAT = "directions_boat"
        const val DIRECTIONS_BUS = "directions_bus"
        const val DIRECTIONS_CAR = "directions_car"
        const val DIRECTIONS_RAILWAY = "directions_railway"
        const val DIRECTIONS_RUN = "directions_run"
        const val DIRECTIONS_SUBWAY = "directions_subway"
        const val DIRECTIONS_TRANSIT = "directions_transit"
        const val DIRECTIONS_WALK = "directions_walk"
        const val DISC_FULL = "disc_full"
        const val DNS = "dns"
        const val DO_NOT_DISTURB = "do_not_disturb"
        const val DO_NOT_DISTURB_ALT = "do_not_disturb_alt"
        const val DO_NOT_DISTURB_OFF = "do_not_disturb_off"
        const val DO_NOT_DISTURB_ON = "do_not_disturb_on"
        const val DOCK = "dock"
        const val DOMAIN = "domain"
        const val DONE = "done"
        const val DISABLE = "Disable"
        const val PAYMENT_IN_PROGRESS = "1"
        const val PURCHASE = "2"
        const val PENDING = "pending"
        const val ACTIVATED = "activated"
        const val cancelled = "cancelled"
        const val EXPIRED ="5"
        const val COMPLETE ="COMPLETE"

    }

}
